# Generated by Django 3.1.1 on 2023-03-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=225)),
                ('cname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=225)),
                ('cid', models.CharField(max_length=225)),
                ('grade', models.CharField(max_length=225)),
                ('classnum', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=225)),
                ('sname', models.CharField(max_length=225)),
                ('classnum', models.CharField(max_length=225)),
                ('s_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=225)),
                ('tname', models.CharField(max_length=255)),
                ('classnum', models.CharField(max_length=225)),
                ('cid', models.CharField(max_length=225)),
                ('appointment', models.CharField(max_length=225)),
                ('t_password', models.CharField(max_length=255)),
            ],
        ),
    ]
