# Generated by Django 3.1.1 on 2023-04-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='cid',
            field=models.CharField(max_length=225, verbose_name='课程号'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cname',
            field=models.CharField(max_length=255, verbose_name='课程名'),
        ),
        migrations.AlterField(
            model_name='score',
            name='cid',
            field=models.CharField(max_length=225, verbose_name='课程号'),
        ),
        migrations.AlterField(
            model_name='score',
            name='classnum',
            field=models.CharField(max_length=225, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='score',
            name='grade',
            field=models.CharField(max_length=225, verbose_name='成绩'),
        ),
        migrations.AlterField(
            model_name='score',
            name='sid',
            field=models.CharField(max_length=225, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classnum',
            field=models.CharField(max_length=225, verbose_name='所在班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_password',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.CharField(max_length=225, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=225, verbose_name='学生姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='appointment',
            field=models.IntegerField(choices=[(0, '学科教师'), (1, '班主任')], max_length=225, verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='cid',
            field=models.CharField(max_length=225, verbose_name='课程号'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classnum',
            field=models.CharField(max_length=225, verbose_name='所带班级'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_password',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tid',
            field=models.CharField(max_length=225, verbose_name='教师号'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tname',
            field=models.CharField(max_length=255, verbose_name='教师名'),
        ),
    ]
