# Generated by Django 3.1.1 on 2023-04-17 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_auto_20230416_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='s_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sname',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='t_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tname',
            new_name='username',
        ),
    ]
